---
  - name: Configure Profile for non ec2
    block:
      - name: Set Default Profile
        template:
          src: "{{ aws_cw_agent_profile_template }}"
          dest: "{{ aws_cw_agent_profile_path }}"
        tags:
          - profile
      - name: Set Default Config for Profile
        template:
          src: "{{ item }}"
          dest: "{{ aws_cw_agent_common_conf_file }} "
        with_first_found:
          - files:
              - "{{ aws_cw_agent_common_template }}"
        tags:
          - config
    when: aws_cw_agent_type !='ec2'
    