---
  - name: Configure Windows Agent
    block:
      - name: deploy windows agent configuration
        template:
          src: "{{ item }}"
          dest: "{{ aws_cw_agent_config_file }}"
        with_first_found:
          - files:
              - "{{ aws_cw_config_template }}"
        tags:
          - config
        register: config

      - name: start windows cloudwatch agent
        win_command: |
          powershell.exe ./amazon-cloudwatch-agent-ctl.ps1 \
              -a fetch-config \
              -m {{ aws_cw_agent_type }} \
              -c file:'{{ aws_cw_agent_config_file }}' \
              -s
        args:
          chdir: "{{ aws_cw_root }}"
        when: config is changed
    when: ansible_os_family == "Windows"