---
- name: restart-cw-agent
  service:
    name: "{{ aws_cw_agent_service }}"
    state: "restarted"

- name: restart-cw-agent-windows
  win_service:
    name: "{{ aws_cw_agent_service }}"
    state: "restarted"